### ISSUE TITLE
Performance Enhancement for information_schema."tables"

### ISSUE THREAD

**Issue by Alain-Barrette** [dremio/dbt-dremio#134]
When we run the code to implement our dremio objects, the following code get run

      select (case when position('.' in table_schema) > 0
              then substring(table_schema, 1, position('.' in table_schema) - 1)
              else table_schema
          end) as table_catalog
          ,table_name
          ,(case when position('.' in table_schema) > 0
              then substring(table_schema, position('.' in table_schema) + 1)
              else 'no_schema'
          end) as table_schema
          ,lower(table_type) as table_type
      from information_schema."tables"
      **where ilike(table_schema, 'Preparation.B2BV.Curated')**
      and table_type <> 'system_table'

The issue is with the where ilike(table_schema, 'Preparation.B2BV.Curated'). By applying a fonction (iLike) on the column, the performance is really bad.  As you can see in the image, 
![image](https://user-images.githubusercontent.com/57188421/219699989-d8e829b0-16bc-4142-ba85-f6bcd0adc4f1.png)

Replacing this ilike with an equality would resolve this issue

where table_schema = 'Preparation.B2BV.Curated'

This would cause dremio to be lightning fast as it should. 

Thanks

**Comment by ArgusLi** [comment]
Thanks for raising the issue! We will be looking into it and get back to you if we have any questions. Thanks once again!

**Comment by fabrice-etanchaud** [comment]
Hi @Alain-Barrette, @ArgusLi,
I totally agree with you, it's far from efficient. But I ended up writing that query that way because there are tricky things concerning character case in dremio. 

dremio is case insensitive with metadata (table, column names), but case sensitive with data (equality, like...). And on top of that dbt could issue warnings like : "When searching for a relation, dbt found an approximate match. Instead of guessing which relation to use, dbt will move on. Please delete database.schema.model, or rename it to be less ambiguous.".

So my two cents advice, be very careful with catalog macros. I will be very pleased to help, if needed.

Best regards,
Fabrice

**Comment by ArgusLi** [comment]
@Alain-Barrette I've started work on this new change. If you look at the associated branch, I have created a new variable `dremio:exact_search_enabled` which defaults to false. However, if you add the following to your project's dbt_project.yml file, it will enable the variable.
```
vars:
    dremio:exact_search_enabled: True
```

Enabling the variable then changes the ilike to a basic equality for the dremio__list_relations_without_caching macro when reflections are also disabled. I've done some basic testing but have not done a full test suite or investigated the consequences of enabling this variable. 

Please feel free to try it out and let me know if there are any bugs or anything else that needs to be changed.

Note: Using this branch requires dbt-core 1.4.1.

**Comment by Alain-Barrette** [comment]
Thank you @ArgusLi , I have created a ticket on my side to have the team validate this. We will keep you informed of the result.

**Comment by alexcotecbq** [comment]
@ArgusLi : not working when installing dbt-core 1.4.1 with dbt-dremio 1.3.2 on the CLI with Python 3.10.  Could you update PyPi?

**Comment by ArgusLi** [comment]
@alexcotecbq In order to test this new change, you'll have to clone the repo, switch to the branch `134-performance-enhancement-for-information_schematables` and [install the local dbt-dremio](https://pip.pypa.io/en/stable/topics/local-project-installs/). Doing `dbt --version` should then show that dbt-dremio and dbt-core are both at 1.4.1.

We only want to update pypi for each release, and this change will most likely be put into the 1.4 release, which should happen pretty soon, most likely within the month.

**Comment by alexcotecbq** [comment]
(dags) cotea@POR771:~/code/dbt-dags$ dbt run --target qa --select Application.3_Jeux_Donnees.VentesVoyage
18:41:05  Encountered an error:
'_MISSING_TYPE' object has no attribute 'replace_dict'
18:41:05  Traceback (most recent call last):
  File "/home/cotea/.virtualenvs/dags/lib/python3.10/site-packages/dbt/main.py", line 135, in main
    results, succeeded = handle_and_check(args)
  File "/home/cotea/.virtualenvs/dags/lib/python3.10/site-packages/dbt/main.py", line 198, in handle_and_check
    task, res = run_from_args(parsed)
  File "/home/cotea/.virtualenvs/dags/lib/python3.10/site-packages/dbt/main.py", line 225, in run_from_args
    task = parsed.cls.from_args(args=parsed)
  File "/home/cotea/.virtualenvs/dags/lib/python3.10/site-packages/dbt/task/base.py", line 186, in from_args
    return super().from_args(args)
  File "/home/cotea/.virtualenvs/dags/lib/python3.10/site-packages/dbt/task/base.py", line 108, in from_args
    config = cls.ConfigType.from_args(args)
  File "/home/cotea/.virtualenvs/dags/lib/python3.10/site-packages/dbt/config/runtime.py", line 265, in from_args
    return cls.from_parts(
  File "/home/cotea/.virtualenvs/dags/lib/python3.10/site-packages/dbt/config/runtime.py", line 84, in from_parts
    .replace_dict(_project_quoting_dict(project, profile))
AttributeError: '_MISSING_TYPE' object has no attribute 'replace_dict'

**Comment by alexcotecbq** [comment]
(dags) cotea@POR771:~/code/dbt-dags$ pip list | grep dbt
dbt-core                                 1.3.2
dbt-dremio                               1.4.1
dbt-extractor                            0.4.1

**Comment by alexcotecbq** [comment]
Okay this, is working.

**Comment by alexcotecbq** [comment]
**Performance without the change (149 seconds)** 

---
(dags) cotea@POR771:~/code/dbt-dags$ dbt compile --target qa
20:25:15  Running with dbt=1.3.2
20:25:15  Unable to do partial parsing because config vars, config profile, or config target have changed
20:25:25  Found 969 models, 20 tests, 0 snapshots, 0 analyses, 331 macros, 0 operations, 0 seed files, 331 sources, 0 exposures, 0 metrics
20:25:25  
20:27:33  Concurrency: 100 threads (target='qa')
20:27:33  
20:27:44  Done.
---


**Performance with the new change (27 seconds):**

---
(dags) cotea@POR771:~/code/dbt-dags$ dbt compile --target qa
18:56:27  Running with dbt=1.4.1
18:56:29  Found 969 models, 20 tests, 0 snapshots, 0 analyses, 334 macros, 0 operations, 0 seed files, 331 sources, 0 exposures, 0 metrics
18:56:29  
18:56:42  Concurrency: 100 threads (target='qa')
18:56:42  
18:56:54  Done.
---

**Comment by Alain-Barrette** [comment]
@ArgusLi , This is much much faster now. 
![image](https://user-images.githubusercontent.com/57188421/222259037-232767df-4dd5-4f7f-9357-2ebfdcdffbf8.png)

@alexcotecbq , Thanks a lot for your implication.
